name: Mickle Corporation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57083
title: Mickle Corporation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d2d8'
    - '#000000'
    - '#1c3031'
    - '#4f6e82'
    - '#7091bc'
  brandStrength: 0.5565975515637547
  lightness: 0.696261951001361
  saturation: 0.8875785921700299
  rhythmicContrast: 0.819977808278054
purpose: []
