name: Mickle Corporation
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13844291190616786
title: Mickle Corporation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bcbcbc'
    - '#e3e3e3'
    - '#525250'
    - '#252525'
  brandStrength: 0.5565975515637547
  lightness: 0.696261951001361
  saturation: 0.8875785921700299
  rhythmicContrast: 0.819977808278054
purpose: []
