name: Mickle Corporation
favicon: null
layout_spectrum: 0.23887766292318702
typography_spectrum: 0.13844291190616786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5565975515637547
  lightness: 0.696261951001361
  saturation: 0.8875785921700299
  rhythmicContrast: 0.819977808278054
purpose: []
